### ISSUE TITLE
Model deadline

### ISSUE THREAD

**Issue by finlayiainmaclean** [causalbench/causalbench-starter#5]
Is the model deadline still 14th April, despite the delay in the challenge starting and the starter repo being available? Thanks!

**Comment by causalbench** [comment]
hi @finlayiainmaclean, thank you very much! No extensions to the deadline are planned. 

We unfortunately do not have flexibility to adjust the timeline because the challenge is linked to the MLDD workshop at ICLR where we plan to announce the winners. Many thanks for your understanding and best of luck! 🥇
